services:
  zookeeper:
    container_name: zookeeper-server
    image: "zookeeper:latest"
    restart: always
    hostname: zoo
    ports: [ "2181:2181" ]
    networks:
      - kafka-net
    environment:
      ZOO_MY_ID: 1
    
  kafka:
    image: ubuntu/kafka
    container_name: kafka-1
    hostname: kafka-1
    ports: [ "9092:9092" ]
    networks:
      - kafka-net
    environment:
      ZOOKEEPER_HOST: zoo
      ZOOKEEPER_PORT: 2181
