name: Run Docker Compose
run-name: self-hosted
on:
  push:
    paths: docker-compose.yaml
    branches: [main]
jobs:
  Run-Docker-Compose:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: podman-compose down
      - run: podman network rm "kafka-types_kafka"
      - run: podman-compose up --detach --build